services:
  mysql:
    image: mysql:8.0
    container_name: mysql_nest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nestjs_db
      MYSQL_USER: nest_user
      MYSQL_PASSWORD: nest_password
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: nest_user
      PMA_PASSWORD: nest_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
